cmd = touch

all: pcan32 pcan31 pcan30 pcan29 pcan28 pcan27
pcan32:
	@${cmd} $@

pcan31:
	@${cmd} $@

pcan30:
	@${cmd} $@

pcan29:
	@${cmd} $@

pcan28:
	@${cmd} $@

pcan27:
	@${cmd} $@

distclean:
	$(RM) pcan*

clean:
	$(RM) pcan*.sock
