######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 26 17:02:00 2008
######################################################################


TEMPLATE = lib
TARGET = pcan
DEPENDPATH += .
INCLUDEPATH += ../inc

STATIC = yes
message("STATIC: $$STATIC")
contains(STATIC, yes) {
  CONFIG += static
}
contains(STATIC, no) {
  CONFIG += shared
}

# Input
SOURCES += libpcan.c

