#! /homes/tofp/c/ruby/bin/ruby

# $Id: cleanup.rb,v 1.3 2008/08/07 18:34:02 tofp Exp $
# Copyright (C) 2007, Kohei Kajimoto. All rights reserved.
 
require 'rubygems'
require 'active_record'

VAR="/data/star/tof/www/var"

ActiveRecord::Base.establish_connection({
      :adapter  => "mysql", 
      :database => "TOF",
#      :socket   => "/tmp/mysql.socket",
      :socket   => "/var/lib/mysql/mysql.sock",
      :username => "tofp",
      :password => "t4flight"
})
class RunConfig < ActiveRecord::Base
    has_many :run
end
class Run < ActiveRecord::Base
  belongs_to :run_config
  has_many :module_result
end
class ModuleResult < ActiveRecord::Base
  belongs_to :run
end

# delete data directories generated by snapshot.rb
Dir.glob("#{VAR}/r/1*") do |f|
  rid = File.basename(f).to_i
  next if Run::find(rid).run_status_id == 2 # skip if it's running
  Dir.glob("#{f}/*") { |ff| File.delete(ff) }
  Dir.rmdir(f)
end

Dir.glob("#{VAR}/r/tmp/200*") do |f|
  Dir.glob("#{f}/*") { |ff| File.delete(ff) }
  Dir.rmdir(f)
end
#

# delete data file in module result directory
Dir.glob("#{VAR}/mr/200*/*.dat")  { |f| File.delete(f) }
Dir.glob("#{VAR}/mr/200*/*.root") { |f| File.delete(f) }
Dir.glob("#{VAR}/mr/200*") do |f|
  dname = File.basename(f).to_i
  next if ModuleResult.count(:conditions => ["data_uri like '%?'", dname]) > 0
  Dir.glob("#{f}/*") { |ff| File.delete(ff) }
  Dir.rmdir(f)
end

# delete data file in tray cosmic directory
Dir.glob("#{VAR}/tr/200*/*.dat")  { |f| File.delete(f) }
Dir.glob("#{VAR}/tr/200*/*.root") { |f| File.delete(f) }
Dir.glob("#{VAR}/tr/200*") do |f|
  dname = File.basename(f).to_i
  next if ModuleResult.count(:conditions => ["data_uri like '%?'", dname]) > 0
  Dir.glob("#{f}/*") { |ff| File.delete(ff) }
  Dir.rmdir(f)
end

# delete data file in submarine result directory
Dir.glob("#{VAR}/sr/200*/*.dat")  { |f| File.delete(f) }
Dir.glob("#{VAR}/sr/200*/*.root") { |f| File.delete(f) }
Dir.glob("#{VAR}/sr/200*") do |f|
  dname = File.basename(f).to_i
  next if ModuleResult.count(:conditions => ["data_uri like '%?'", dname]) > 0
  Dir.glob("#{f}/*") { |ff| File.delete(ff) }
  Dir.rmdir(f)
end
