######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 20 20:10:49 2008
######################################################################

TEMPLATE = subdirs
SUBDIRS += src app
CONFIG += debug

debug {
  SUBDIRS += fakepcan dev
}
