######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 20 20:10:49 2008
######################################################################

TEMPLATE = subdirs
CONFIG += debug

#debug {
#  SUBDIRS += fakepcan
#}

SUBDIRS += src app
